apiVersion: v2
name: traefik-umbrella
version: 0.0.2
description: A Traefik umbrella chart with custom middleware
dependencies:
- name: traefik
  version: "38.0.2"
  repository: https://traefik.github.io/charts
