apiVersion: v2
name: prometheus
version: 0.0.1
description: A prometheus umbrella chart
dependencies:
- name: kube-prometheus-stack
  version: "81.5.0"
  repository: https://prometheus-community.github.io/helm-charts