apiVersion: v2
name: wadebridge-games
description: A Helm chart for the Wadebridge Games application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: postgresql
  version: "18.1.10"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled