---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: wadebridge-games-uk-production
    namespace: webapps
spec:
    secretName: wadebridge-games-uk-production-tls
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
    commonName: "*.wadebridgegames.uk"
    dnsNames:
    - "wadebridgegames.uk"
    - "*.wadebridgegames.uk"
