apiVersion: v2
name: loki-umbrella
version: 0.0.1
description: A loki umbrella chart
dependencies:
- name: promtail
  version: "6.17.1"
  repository: https://grafana.github.io/helm-charts
- name: grafana
  version: "10.5.15"
  repository: https://grafana.github.io/helm-charts