---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wadebridge-games
  namespace: webapps
  labels:
    app: wadebridge-games
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: wadebridge-games
  template:
    metadata:
      labels:
        app: wadebridge-games
    spec:
      containers:
      - name: wadebridge-games
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - secretRef:
            name: wadebridge-games-env
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z {{ .Release.Name }}-postgresql 5432; do echo waiting for postgres; sleep 2; done"]
      - name: pg-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ['sh', '-c', "npx prisma@6 migrate deploy"]
        envFrom:
        - secretRef:
            name: wadebridge-games-env

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pgadmin
  namespace: webapps
  labels:
    app: pgadmin
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-data
      containers:
      - name: pgadmin
        image: "dpage/pgadmin4:latest"
        envFrom:
        - secretRef:
            name: wadebridge-pgadmin-credentials
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin