---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wadebridge-games-offical
  namespace: webapps
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wadebridgegames.newlinkedlist.uk`) || Host(`www.wadebridgegames.newlinkedlist.uk`)
      kind: Rule
      services:
        - name: wadebridge-games
          port: 80
  tls:
    secretName: wadebridge-games-uk-production-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pg-wadebridge-games
  namespace: webapps
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pg.wadebridgegames.newlinkedlist.uk`)
      kind: Rule
      services:
        - name: wadebridge-games-pg-admin
          port: 80
  tls:
    secretName: wadebridge-games-uk-production-tls