apiVersion: v2
name: wadebridge-games-dev
description: A Helm chart for the Wadebridge Games application DEV BUILD
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: postgresql
  version: "18.2.1"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled